name: commit
on:
  push:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
      - run: yarn --frozen-lockfile
      - name: deploy staging
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login docker.io --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
          sh deploy.sh staging

  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
      - run: yarn --frozen-lockfile
      - uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        with:
          publish: |
            docker login docker.io --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            sh deploy.sh production
          createGithubReleases: true
