name: commit
on:
  push:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
      - run: yarn --frozen-lockfile
      - run: 'docker build --tag cloudwalker/changesets-for-apps:${{git rev-parse --short HEAD}} .'

  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
      - run: yarn --frozen-lockfile
      - uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          publish: |
            docker build --tag cloudwalker/changesets-for-apps:${{jq -r .version package.json}} .

          createGithubReleases: true
